// Generated by Arma 3 Dialog Creator v0.1.0
class RscButton;
class RscEdit;
class RscText;
// Dialog display
class SQF_UserInput_Dialog
{
    idd = 85407;
    movingEnable = 0;
    enableSimulation = 1;
    onLoad = "uiNamespace setVariable ['SQF_UserInput_Dialog_Display', _this select 0]; ['onLoad', _this] call SQF_UserInput_Dialog_fnc_onDisplay";
    onUnload = "uiNamespace setVariable ['SQF_UserInput_Dialog_Display', displayNull]; ['onUnload', _this] call SQF_UserInput_Dialog_fnc_onDisplay";

    class controlsBackground
    {
        class SQF_Background_Text: RscText
        {
            idc = 86408;
            text = "";
            font = "RobotoCondensed";
            style = 0;
            sizeEx = 0.04;
            x = "safeZoneX + safeZoneW * 0.475";
            y = "safeZoneY + safeZoneH * 0.4";
            w = "safeZoneW * 0.15";
            h = "safeZoneH * 0.15";
            colorText[] = {1,1,1,1};
            colorBackground[] = {0,0,0,1};
            // editor: visible=true; locked=false; background=true;
        };
    };

    class controls
    {
        class SQF_Display_Text: RscText
        {
            idc = 86409;
            text = "Set Pronouns";
            font = "RobotoCondensed";
            style = 0;
            sizeEx = 0.04;
            x = "safeZoneX + safeZoneW * 0.475";
            y = "safeZoneY + safeZoneH * 0.4";
            w = "safeZoneW * 0.15";
            h = "safeZoneH * 0.05";
            colorText[] = {1,1,1,1};
            colorBackground[] = {0,0,0,0};
            // editor: visible=true; locked=false; background=false;
        };
        class SQF_Input_Edit: RscEdit
        {
            idc = 86410;
            font = "RobotoCondensed";
            style = 0;
            sizeEx = 0.04;
            x = "safeZoneX + safeZoneW * 0.475";
            y = "safeZoneY + safeZoneH * 0.45";
            w = "safeZoneW * 0.15";
            h = "safeZoneH * 0.05";
            colorText[] = {1,1,1,1};
            colorBackground[] = {0,0,0,0};
            // editor: visible=true; locked=false; background=false;
        };
        class SQF_Apply_Button: RscButton
        {
            idc = 86411;
            text = "Apply";
            action = "call SQF_fnc_selectPronoun;";
            font = "RobotoCondensed";
            style = 0;
            sizeEx = 0.04;
            x = "safeZoneX + safeZoneW * 0.475";
            y = "safeZoneY + safeZoneH * 0.5";
            w = "safeZoneW * 0.15";
            h = "safeZoneH * 0.05";
            colorText[] = {1,1,1,1};
            colorBackground[] = {0,0,0,0};
            // editor: visible=true; locked=false; background=false;
        };
    };
};

