// Generated by Arma 3 Dialog Creator v0.1.0

#include "../include.hpp"

class RscButton;
class RscText;
class RscEdit;

// Dialog display
class SQF_UserInput_Dialog
{
    idd = 85407;
    movingEnable = 0;
    enableSimulation = 1;
    onLoad = "uiNamespace setVariable ['SQF_UserInput_Dialog_Display', _this select 0]; ['onLoad', _this] call SQF_UserInput_Dialog_fnc_onDisplay";
    onUnload = "uiNamespace setVariable ['SQF_UserInput_Dialog_Display', displayNull]; ['onUnload', _this] call SQF_UserInput_Dialog_fnc_onDisplay";

    class controlsBackground
    {
        class SQF_Background_Text: RscText
        {
            idc = 86408;
            text = "";
            font = "RobotoCondensed";
            style = 0;
            sizeEx = 0.04;
            x = "safeZoneX + safeZoneW * 0.4";
            y = "safeZoneY + safeZoneH * 0.4";
            w = "safeZoneW * 0.33";
            h = "safeZoneH * 0.1";
            colorText[] = {1,1,1,1};
            colorBackground[] = {0,0,0,1};
            // editor: visible=true; locked=false; background=true;
        };
    };

    class controls
    {
        class SQF_Display_Text: RscText
        {
            idc = 86409;
            text = "Set Pronouns";
            font = "RobotoCondensed";
            style = 0;
            sizeEx = 0.04;
            x = "safeZoneX + safeZoneW * 0.4";
            y = "safeZoneY + safeZoneH * 0.4";
            w = "safeZoneW * 0.18";
            h = "safeZoneH * 0.055";
            colorText[] = {1,1,1,1};
            colorBackground[] = {0,0,0,0};
            // editor: visible=true; locked=false; background=false;
        };
        class SQF_Input_Edit: RscEdit
        {
            idc = 86410;
            font = "RobotoCondensed";
            style = 0;
            sizeEx = 0.04;
            x = "safeZoneX + safeZoneW * 0.4";
            y = "safeZoneY + safeZoneH * 0.45";
            w = "safeZoneW * 0.2";
            h = "safeZoneH * 0.055";
            colorText[] = {1,1,1,1};
            colorBackground[] = {0,0,0,0};
            // editor: visible=true; locked=false; background=false;
        };
        class SQF_Apply_Button: RscButton
        {
            idc = 86411;
            text = "Apply";
            action = "call SQF_fnc_selectPronoun;";
            font = "RobotoCondensed";
            style = 0;
            sizeEx = 0.04;
            x = "safeZoneX + safeZoneW * 0.6";
            y = "safeZoneY + safeZoneH * 0.45";
            w = "safeZoneW * 0.13";
            h = "safeZoneH * 0.055";
            colorText[] = {1,1,1,1};
            colorBackground[] = {0,0,0,0};
            // editor: visible=true; locked=false; background=false;
        };
    };
};

// Suggested lifecycle stub:
// SQF_UserInput_Dialog_fnc_onDisplay = {
//     params [['_phase', '', ['']], ['_args', [], [[]]]];
//     private _display = _args param [0, displayNull, [displayNull]];
//     if (isNull _display) exitWith {false};
//     true
// };

// Suggested action handler: TAG_fnc_dialogAction
// TAG_fnc_dialogAction = {
//     params [['_case', '', ['']], ['_args', [], [[]]]];
//     switch (_case) do {
//         case "Button_3": {
//         };
//         default {};
//     };
// };
